force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booth__c/Booth__c.object-meta.xml
<CustomObject>
    <label>Booth</label>
    <nameField>
        <label>Booth Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booths</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booth__c/fields/Booth_Name__c.field-meta.xml
<CustomField>
    <fullName>Booth_Name__c</fullName>
    <label>Booth Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booth__c/fields/Cloud_Focus__c.field-meta.xml
<CustomField>
    <fullName>Cloud_Focus__c</fullName>
    <label>Cloud Focus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skill</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booth__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booth__c/fields/Required_Function__c.field-meta.xml
<CustomField>
    <fullName>Required_Function__c</fullName>
    <label>Required Function</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booth__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <referenceTo>Section__c</referenceTo>
    <relationshipName>Pods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shift__c/Shift__c.object-meta.xml
<CustomObject>
    <label>Shift</label>
    <nameField>
        <displayFormat>Sh-{00000}</displayFormat>
        <label>Shift Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shift__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <label>End</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shift__c/fields/Pod__c.field-meta.xml
<CustomField>
    <fullName>Pod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pod</label>
    <referenceTo>Booth__c</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shift__c/fields/Shift_Order__c.field-meta.xml
<CustomField>
    <fullName>Shift_Order__c</fullName>
    <label>Shift Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shift__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <label>Staff</label>
    <nameField>
        <label>Staff Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff__c/fields/Cloud__c.field-meta.xml
<CustomField>
    <fullName>Cloud__c</fullName>
    <label>Cloud</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skill</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff__c/fields/is_manager__c.field-meta.xml
<CustomField>
    <fullName>is_manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Staff__c</referenceTo>
    <relationshipLabel>Staff</relationshipLabel>
    <relationshipName>Staff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staff__c/fields/Shift_Constraints__c.field-meta.xml
<CustomField>
    <fullName>Shift_Constraints__c</fullName>
    <label>Shift Constraints</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1_1</fullName>
            </value>
            <value>
                <fullName>1_2</fullName>
            </value>
            <value>
                <fullName>1_3</fullName>
            </value>
            <value>
                <fullName>1_4</fullName>
            </value>
            <value>
                <fullName>2_1</fullName>
            </value>
            <value>
                <fullName>2_2</fullName>
            </value>
            <value>
                <fullName>2_3</fullName>
            </value>
            <value>
                <fullName>2_4</fullName>
            </value>
            <value>
                <fullName>3_1</fullName>
            </value>
            <value>
                <fullName>3_2</fullName>
            </value>
            <value>
                <fullName>3_3</fullName>
            </value>
            <value>
                <fullName>3_4</fullName>
            </value>
            <value>
                <fullName>4_1</fullName>
            </value>
            <value>
                <fullName>4_2</fullName>
            </value>
            <value>
                <fullName>4_3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff_on_Shift__c/Staff_on_Shift__c.object-meta.xml
<CustomObject>
    <label>Staff on Shift</label>
    <nameField>
        <displayFormat>SoSId-{000000}</displayFormat>
        <label>Staff on Shift Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff on Shift</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_on_Shift__c/fields/Shift__c.field-meta.xml
<CustomField>
    <fullName>Shift__c</fullName>
    <label>Shift</label>
    <referenceTo>Shift__c</referenceTo>
    <relationshipLabel>Staff</relationshipLabel>
    <relationshipName>Staff</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Staff_on_Shift__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <referenceTo>Staff__c</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Function.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>BDR</fullName>
    </customValue>
    <customValue>
        <fullName>CSG</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>GTM</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>non-technical</fullName>
    </customValue>
    <customValue>
        <fullName>PAM</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Enablement</fullName>
    </customValue>
    <customValue>
        <fullName>SDR</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <masterLabel>Function</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>CPG/Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma</fullName>
    </customValue>
    <customValue>
        <fullName>SMB</fullName>
    </customValue>
    <customValue>
        <fullName>Telco</fullName>
    </customValue>
    <masterLabel>Industry</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Skill.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Quip</fullName>
    </customValue>
    <customValue>
        <fullName>Community</fullName>
    </customValue>
    <customValue>
        <fullName>Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <masterLabel>Skill</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CebitShiftController.cls
public class CebitShiftController {
	@AuraEnabled
	public static CebitShiftWrapper getData(String type){
			List<Staff__c> staff = [SELECT Id, Name, Available__c, Cloud__c, Industry__c, Function__c, is_manager__c, Manager__c, Shift_Constraints__c FROM Staff__c WHERE Function__c = :type ORDER BY Last_Name__c ASC NULLS FIRST];
        	List<Booth__c> boothList = [SELECT Id, 
                                        		Name, 
                                        		Booth_Name__c, 
                                        		Cloud_Focus__c, 
                                        		Required_Function__c, 
                                        		Industry__c,
                                        		Section__r.Name, 
                                        		Section__r.Area__r.Name,
                                        		(Select Id, Date__c, Start__c, End__c, Shift_Order__c 
                                                 From Shifts__r
                                                ORDER BY Shift_Order__c ASC NULLS FIRST)
                                        FROM Booth__c
                                       	ORDER BY Name ASC NULLS FIRST];
        	List<Staff_on_Shift__c> staffShiftList = [SELECT Id, Shift__r.Shift_Order__c, Shift__r.Date__c, Staff__r.Name FROM Staff_on_Shift__c];
		return new CebitShiftWrapper(staff, boothList,staffShiftList);
	}
    
    @AuraEnabled
    public static Boolean updateStaffAssignment(List<Staff_on_Shift__c> addAssignments, List<Staff_on_Shift__c> removeAssignments){
			insert addAssignments;
        	delete removeAssignments;
		return true;
    }
}