force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booth__c/Booth__c.object-meta.xml
<CustomObject>
    <label>Booth</label>
    <nameField>
        <label>Booth Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booths</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booth__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <referenceTo>Section__c</referenceTo>
    <relationshipName>Pods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <label>Staff</label>
    <nameField>
        <label>Staff Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_on_Shift__c/Staff_on_Shift__c.object-meta.xml
<CustomObject>
    <label>Staff on Shift</label>
    <nameField>
        <displayFormat>SoSId-{000000}</displayFormat>
        <label>Staff on Shift Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff on Shift</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_on_Shift__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <referenceTo>Staff__c</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CebitShiftWrapper.cls
public class CebitShiftWrapper {
 @AuraEnabled public List<Staff__c> Staff { get; set; }
 @AuraEnabled public List<Booth__c> BoothList { get; set; }
 @AuraEnabled public List<Staff_on_Shift__c> StaffShiftList {get; set; }
 @AuraEnabled public List<String> areaFilterOptions {get; set; }
 @AuraEnabled public List<String> sectionFilterOptions {get; set; }


    // Trivial constructor, for server-side Apex -> client-side JavaScript
    public CebitShiftWrapper(List<Staff__c> staff, List<Booth__c> boothList, List<Staff_on_Shift__c> StaffShiftList) {
        this.Staff = staff;
        this.BoothList = boothList;
        this.StaffShiftList = StaffShiftList;
        Set<String> afo = new Set<String>();
        Set<String> sfo = new Set<String>();
        for(Booth__c b : boothList){
            sfo.add(b.Section__r.Name);
            afo.add(b.Section__r.Area__r.Name);
        }
        this.areaFilterOptions = new List<String>(afo);
        this.sectionFilterOptions = new List<String>(sfo);
       }

    // Default, no-arg constructor, for client-side -> server-side
    public CebitShiftWrapper() {}
    
}