force-app/main/default/objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <label>Staff</label>
    <nameField>
        <label>Staff Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff__c/fields/Cloud__c.field-meta.xml
<CustomField>
    <fullName>Cloud__c</fullName>
    <label>Cloud</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skill</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Function</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff__c/fields/is_manager__c.field-meta.xml
<CustomField>
    <fullName>is_manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Staff__c</referenceTo>
    <relationshipLabel>Staff</relationshipLabel>
    <relationshipName>Staff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staff__c/fields/Shift_Constraints__c.field-meta.xml
<CustomField>
    <fullName>Shift_Constraints__c</fullName>
    <label>Shift Constraints</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1_1</fullName>
            </value>
            <value>
                <fullName>1_2</fullName>
            </value>
            <value>
                <fullName>1_3</fullName>
            </value>
            <value>
                <fullName>1_4</fullName>
            </value>
            <value>
                <fullName>2_1</fullName>
            </value>
            <value>
                <fullName>2_2</fullName>
            </value>
            <value>
                <fullName>2_3</fullName>
            </value>
            <value>
                <fullName>2_4</fullName>
            </value>
            <value>
                <fullName>3_1</fullName>
            </value>
            <value>
                <fullName>3_2</fullName>
            </value>
            <value>
                <fullName>3_3</fullName>
            </value>
            <value>
                <fullName>3_4</fullName>
            </value>
            <value>
                <fullName>4_1</fullName>
            </value>
            <value>
                <fullName>4_2</fullName>
            </value>
            <value>
                <fullName>4_3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Function.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>BDR</fullName>
    </customValue>
    <customValue>
        <fullName>CSG</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>GTM</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>non-technical</fullName>
    </customValue>
    <customValue>
        <fullName>PAM</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Enablement</fullName>
    </customValue>
    <customValue>
        <fullName>SDR</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <masterLabel>Function</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>CPG/Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma</fullName>
    </customValue>
    <customValue>
        <fullName>SMB</fullName>
    </customValue>
    <customValue>
        <fullName>Telco</fullName>
    </customValue>
    <masterLabel>Industry</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Skill.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Quip</fullName>
    </customValue>
    <customValue>
        <fullName>Community</fullName>
    </customValue>
    <customValue>
        <fullName>Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <masterLabel>Skill</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CebitStaffController.cls
public class CebitStaffController {
	@AuraEnabled
	public static CebitStaffWrapper getStaff(String type){
			List<Staff__c> staff = [SELECT Id, Name, Available__c, Cloud__c, Industry__c, Function__c, is_manager__c, Manager__c, Shift_Constraints__c FROM Staff__c WHERE Function__c = :type ORDER BY Last_Name__c ASC NULLS FIRST];
		return new CebitStaffWrapper(staff);
	}

	@AuraEnabled
	public static CebitStaffWrapper updateStaff(String type, List<Staff__c> staffUpdate){
		update staffUpdate;
		List<Staff__c> staff = [SELECT Id, Name, Available__c, Cloud__c, Industry__c, Function__c, is_manager__c, Manager__c, Shift_Constraints__c FROM Staff__c WHERE Function__c = :type ORDER BY Last_Name__c ASC NULLS FIRST];
		return new CebitStaffWrapper(staff);
	}
}