force-app/main/default/objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <label>Staff</label>
    <nameField>
        <label>Staff Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff__c/fields/Cloud__c.field-meta.xml
<CustomField>
    <fullName>Cloud__c</fullName>
    <label>Cloud</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skill</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff__c/fields/Shift_Constraints__c.field-meta.xml
<CustomField>
    <fullName>Shift_Constraints__c</fullName>
    <label>Shift Constraints</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1_1</fullName>
            </value>
            <value>
                <fullName>1_2</fullName>
            </value>
            <value>
                <fullName>1_3</fullName>
            </value>
            <value>
                <fullName>1_4</fullName>
            </value>
            <value>
                <fullName>2_1</fullName>
            </value>
            <value>
                <fullName>2_2</fullName>
            </value>
            <value>
                <fullName>2_3</fullName>
            </value>
            <value>
                <fullName>2_4</fullName>
            </value>
            <value>
                <fullName>3_1</fullName>
            </value>
            <value>
                <fullName>3_2</fullName>
            </value>
            <value>
                <fullName>3_3</fullName>
            </value>
            <value>
                <fullName>3_4</fullName>
            </value>
            <value>
                <fullName>4_1</fullName>
            </value>
            <value>
                <fullName>4_2</fullName>
            </value>
            <value>
                <fullName>4_3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>CPG/Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma</fullName>
    </customValue>
    <customValue>
        <fullName>SMB</fullName>
    </customValue>
    <customValue>
        <fullName>Telco</fullName>
    </customValue>
    <masterLabel>Industry</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Skill.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Quip</fullName>
    </customValue>
    <customValue>
        <fullName>Community</fullName>
    </customValue>
    <customValue>
        <fullName>Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <masterLabel>Skill</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CebitStaffWrapper.cls
public class CebitStaffWrapper {
 @AuraEnabled public List<Staff__c> Staff { get; set; }
 @AuraEnabled public List<String> ConstraintOptions { get; set; }
 @AuraEnabled public List<String> SkillOptions { get; set; }
 @AuraEnabled public List<String> IndustryOptions { get; set; }


    // Trivial constructor, for server-side Apex -> client-side JavaScript
    public CebitStaffWrapper(List<Staff__c> staff) {
        this.Staff = staff;
        List<Schema.PicklistEntry> pick_list_values = Staff__c.Shift_Constraints__c.getDescribe().getPickListValues();
				List<String> constraintOptions = new List<String>();
				for(Schema.PicklistEntry p : pick_list_values){
					constraintOptions.add(p.getValue());
				}
        this.ConstraintOptions = constraintOptions;
        List<Schema.PicklistEntry> pick_list_values_cloud = Staff__c.Cloud__c.getDescribe().getPickListValues();
				List<String> SkillOptions = new List<String>();
				for(Schema.PicklistEntry p : pick_list_values_cloud){
					SkillOptions.add(p.getValue());
				}
        this.SkillOptions = SkillOptions;
        List<Schema.PicklistEntry> pick_list_values_industry = Staff__c.Industry__c.getDescribe().getPickListValues();
				List<String> IndustryOptions = new List<String>();
				for(Schema.PicklistEntry p : pick_list_values_industry){
					IndustryOptions.add(p.getValue());
				}
        this.IndustryOptions = IndustryOptions;
       }

    // Default, no-arg constructor, for client-side -> server-side
    public CebitStaffWrapper() {}
}